// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function CreateAdjective(arg1:model.Adjective):Promise<model.Adjective>;

export function DeleteAdjective(arg1:number):Promise<void>;

export function ListAdjectives():Promise<Array<model.Adjective>>;

export function LoadUIConfig():Promise<main.UIConfig>;

export function SaveUIConfig(arg1:main.UIConfig):Promise<void>;

export function SearchAdjectives(arg1:string):Promise<Array<model.Adjective>>;

export function UpdateAdjective(arg1:model.Adjective):Promise<void>;
