// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAdjective(arg1) {
  return window['go']['main']['App']['CreateAdjective'](arg1);
}

export function DeleteAdjective(arg1) {
  return window['go']['main']['App']['DeleteAdjective'](arg1);
}

export function ListAdjectives() {
  return window['go']['main']['App']['ListAdjectives']();
}

export function LoadUIConfig() {
  return window['go']['main']['App']['LoadUIConfig']();
}

export function SaveUIConfig(arg1) {
  return window['go']['main']['App']['SaveUIConfig'](arg1);
}

export function SearchAdjectives(arg1) {
  return window['go']['main']['App']['SearchAdjectives'](arg1);
}

export function UpdateAdjective(arg1) {
  return window['go']['main']['App']['UpdateAdjective'](arg1);
}
